version: '3.8'
services:
  database:
    container_name: database
    image: mysql:8.3.0
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: monitoring
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - 3306:3306
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
        - '8088:80'
    restart: always
    environment:
        PMA_HOST: database
    depends_on:
        - database
  backend:
    build:
      context: ./backend
    restart: always
    ports:
      - 5000:5000  # Port Flask API

  frontend:
    build:
      context: ./frontend
    restart: always
    ports:
      - 8080:80  # Port Frontend

volumes:
  db:
